protected/models/Artist.php
<?php

/**
 *   Artist - model to store artist`s data in mongodb.
 */

class Artist extends EMongoDocument {

    public $surName;
    public $firstName;
    public $middleName;

    public $description;

    public $phone;
    public $skype;
    public $email;

    /** @virtual */
    public $img;

    public function collectionName()
    {
        return 'artists';
    }

    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function rules()
    {
        return array(
            array('surName,firstName,middleName,description,email', 'required'),
            array('surName,firstName,middleName,description,phone,skype,email', 'type', 'type' => 'string'),
            array('surName,firstName,middleName', 'length', 'max' => 20),
            array('description', 'length', 'max' => 500),
            array('skype', 'match', 'pattern' => '/^[a-zA-Z][a-zA-Z0-9\.,\-_]{5,31}$/'),
            array('phone', 'match', 'pattern' => '/^0?(39|50|63|66|67|68|91|92|93|94|95|96|97|98|99)+?\d{7}$/'),
            array('email', 'email', 'checkMX' => TRUE),

            array('img', 'file', 'mimeTypes' => 'image/jpeg', 'allowEmpty' => true, 'safe' => true, 'on' => 'update'),
            array('img', 'file', 'mimeTypes' => 'image/jpeg', 'allowEmpty' => false, 'safe' => true, 'on' => 'insert'),
        );
    }

    public function attributeNames()
    {
        return array('surName', 'firstName', 'middleName', 'description', 'skype', 'phone', 'email');
    }

    public function attributeLabels()
    {
        return array(
            'firstName'     => 'First Name',
            'surName'       => 'Surname',
            'middleName'    => 'Middle name',
            'description'   => 'Description',
            'skype'         => 'Skype',
            'phone'         => 'Phone Number',
            'email'         => 'E-mail',
            'img'           => 'Image'
        );
    }

    public function getFullName()
    {
        return $this->surName . " " . $this->firstName . " " . $this->middleName;
    }

    public function getPictures()
    {
        $models = Picture::model()->findAll(array('artistId' => (string) $this->_id));
        $categories = array();
        foreach($models as $model){
            $category = $model->category->name;
            if(array_key_exists($category, $categories)) {
                array_push($categories[$category], $model);
            } else {
                $categories[$category] = array($model);
            }
        }
        return $categories;
    }

    protected function afterSave()
    {
        $image = EMongoFile::populate($this,'img');
        if(!is_null($image)) {
            $oldImage = EMongoFile::model()->findOne(array('entityId' => $this->_id));
            if(!is_null($oldImage)) $oldImage->delete();
            $image->entityId = $this->_id;
            return $image->save();
        }
    }

    protected function beforeDelete()
    {
        if(Picture::model()->exists(array('artistId' => (string) $this->_id))){
            return false;
        }
        $image = EMongoFile::model()->findOne(array('entityId' => $this->_id));
        if(is_null($image) || $image->delete()) {
            return parent::beforeDelete();
        } else {
            return false;
        }
    }

}

protected/controllers/ArtistController.php
<?php

class ArtistController extends Controller
{

    public function actionAdmin()
    {
        $dataProvider = new EMongoDataProvider('Artist');
        $this->render('admin', array('dataProvider' => $dataProvider));
    }

    public function actionView()
    {
        $model = $this->loadArtistModel();
        if(!is_null($model)) {
            $this->render('view', array('model' => $model));
        } else {
            $this->redirect(array('site/index'));
        }
    }

    public function actionCreate()
    {
        $model = new Artist();

        if (isset($_POST['Artist'])) {
            $model->attributes = $_POST['Artist'];
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Artist saved');
                $this->redirect('admin');
            }
        }

        $this->render('form', array('model' => $model));
    }

    public function actionDelete()
    {
        if(!Yii::app()->request->getIsAjaxRequest() || $_GET['ajax'] !== 'yw0') {
            throw new CHttpException(400, 'Not ajax request');
        }

        $model = $this->loadArtistModel();
        if(!is_null($model)) {
            if(!$model->delete()) {
                throw new CHttpException(500, 'Artist can`t be deleted');
            }
        } else {
            throw new CHttpException(400, 'Invalid request');
        }
    }

    public function actionUpdate()
    {
        $model = $this->loadArtistModel();
        if(is_null($model) && !isset($_POST['Artist'])) {
            Yii::app()->user->setFlash('message', 'Invalid request');
            $this->redirect(array('artist/admin'));
        } elseif (isset($_POST['Artist'])) {
            $model->attributes = $_POST['Artist'];
            //die(var_dump($model));
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Artist saved');
                $this->redirect(array('artist/admin'));
            }
        }

        $this->render('form', array('model' => $model));
    }

    public function actionJsonData()
    {
        if(!Yii::app()->request->getIsAjaxRequest()) {
            throw new CHttpException(400, 'Not ajax request');
        }

        $model = $this->loadArtistModel();
        if(!is_null($model)) {
            echo $model->getJSONDocument();
        } else {
            throw new CHttpException(400, 'Invalid request');
        }
    }

    private function loadArtistModel()
    {
        if(isset($_GET['id'])) {
            $id = $_GET['id'];
            $model = Artist::model()->findBy_id($id);
            if(is_null($model)) {
                throw new CHttpException(404, 'No such artist');
            }
            return $model;
        } else {
            return null;
        }
    }
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    /**
     * Declares class-based actions.
     */
    public function actions ()
    {
        return array(

            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		$pictures = Picture::model()->find()->limit(4);
        $categories = Category::model()->findAll();
        $artists = Artist::model()->findAll();

		$this->render('index', array('pictures' => $pictures, 'categories' => $categories, 'artists' => $artists));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	public function actionImage()
    {
        if(!isset($_GET['id'])) {
            throw new CHttpException(400, 'Image id not included in request');
        }
        $id = $_GET['id'];
        $image = EMongoFile::model()->findOne(array('entityId' => new MongoId($id)));
        if(!is_null($image)) {
            header('Content-type: image/jpeg');
            echo $image->getBytes();
        } else {
            throw new CHttpException(404, 'No such image');
        }
    }
}

protected/views/artist/admin.php
<?php $this->pageTitle = Yii::app ()->name . ' - Artist'; ?>

<div>
<?php
if(Yii::app()->user->hasFlash('message')) {
   echo CHtml::encode(Yii::app()->user->getFlash('message'));
}
?>
</div>

<?php

echo CHtml::link('Add artist', $this->createUrl('artist/create'));

$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $dataProvider,
    'columns' => array(
        'surName:html',
        'firstName:html',
        'middleName:html',
        array(
            'class'=>'CButtonColumn'
        )
    )
));
?>

protected/views/artist/form.php
<?php
$this->pageTitle = Yii::app ()->name . ' - Artist';

$form = $this->beginWidget ('CActiveForm', array(
    'enableClientValidation' => true,
    'clientOptions' => array(
        'validateOnSubmit' => true,
    ),
    'htmlOptions' => array(
        'name' => 'artist',
        'enctype' => 'multipart/form-data'
    )
)); ?>

<div class="row">
    <?php echo $form->textField($model, 'firstName', array(
        'placeholder' => $model->getAttributeLabel('firstName'),

    )); ?>
    <?php echo $form->error($model,'firstName'); ?>
</div>

<div class="row">
    <?php echo $form->textField($model, 'middleName', array(
        'placeholder' => $model->getAttributeLabel('middleName'),

    )); ?>
    <?php echo $form->error($model,'middleName'); ?>
</div>

<div class="row">
    <?php echo $form->textField($model, 'surName', array(
        'placeholder' => $model->getAttributeLabel('surName'),

    )); ?>
    <?php echo $form->error($model,'surName'); ?>
</div>

<div class="row">
    <?php echo $form->textArea($model, 'description', array(
        'placeholder' => $model->getAttributeLabel('description'),

    )); ?>
    <?php echo $form->error($model,'description'); ?>
</div>

<div class="row">
    <?php echo $form->emailField($model, 'email', array(
        'placeholder' => $model->getAttributeLabel('email'),

    )); ?>
    <?php echo $form->error($model,'email'); ?>
</div>

<div class="row">
    <?php echo $form->textField($model, 'skype', array(
        'placeholder' => $model->getAttributeLabel('skype'),

    )); ?>
    <?php echo $form->error($model,'skype'); ?>
</div>

<div class="row">
    <?php echo $form->textField($model, 'phone', array(
        'placeholder' => $model->getAttributeLabel('phone'),
    )); ?>
    <?php echo $form->error($model,'phone'); ?>
</div>

<div class="row">
    <?php echo $form->labelEx($model,'img'); ?>
    <?php echo $form->fileField($model, 'img'); ?>
    <?php echo $form->error($model,'img'); ?>
</div>

<?php echo CHtml::submitButton ('Save'); ?>

<?php $this->endWidget (); ?>

protected/views/artist/view.php
<?php $this->pageTitle = Yii::app ()->name . ' - ' . $model->fullName; ?>

<div class="page-header">
    <h1><?php echo CHtml::encode($model->fullName) ?></h1>
</div>


<div class="blog-image"><?php echo CHtml::image($this->createUrl('site/image', array('id' => $model->_id)), "No image for this picture", array('class' => 'img-polaroid')); ?></div>

<div class="row-fluid">
    <div class="span12">
        <h3 class="header"><?php echo $model->getAttributeLabel('description') ?>
            <span class="header-line"></span>
        </h3>
        <?php echo CHtml::encode($model->description) ?>
    </div>

</div><!--/row-fluid-->

<?php foreach($model->pictures as $category=>$pictures ): ?>

    <div class="row-fluid">
        <div class="span12">
            <h3 class="header"><?php echo CHtml::encode($category) ?>
                <span class="header-line"></span>
            </h3>
            <?php $this->renderPartial('//picture/_pictures', array('pictures' => $pictures)); ?>
        </div>

    </div><!--/row-fluid-->

<?php endforeach; ?>