protected/models/Picture.php
<?php
/**
 * Picture - model to store pictures data in mongodb
 */

class Picture extends EMongoDocument {

    public $name;
    public $description;
    public $price;

    public $categoryId;
    public $artistId;

    /** @virtual */
    public $img;

    public function collectionName()
    {
        return 'pictures';
    }

    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function rules()
    {
        return array(
            array('name,description,price,categoryId,artistId', 'required'),
            array('name,description', 'type', 'type' => 'string'),
            array('name', 'length', 'max' => 20),
            array('description', 'length', 'max' => 500),
            array('price', 'match', 'pattern' => '/^\d+[\.,]?\d{0,2}$/'),

            array('artistId', 'EMongoExistValidator', 'className' => 'Artist', 'mongoId' => true, 'attributeName' => '_id'),
            array('categoryId', 'EMongoExistValidator', 'className' => 'Category', 'mongoId' => true, 'attributeName' => '_id'),

            array('img', 'file', 'mimeTypes' => 'image/jpeg', 'allowEmpty' => true, 'safe' => true, 'on' => 'update'),
            array('img', 'file', 'mimeTypes' => 'image/jpeg', 'allowEmpty' => false, 'safe' => true, 'on' => 'insert'),
        );
    }

    public function attributeNames()
    {
        return array('name', 'description', 'price', 'category', 'artist');
    }

    public function attributeLabels()
    {
        return array(
            'name'        => 'Name',
            'description' => 'Description',
            'price'       => 'Price',
            'category'    => 'Category',
            'artist'      => 'Artist',
            'img'         => 'Image'
        );
    }

    public function getArtist()
    {
        return Artist::model()->findOne(array('_id' => new MongoId($this->artistId)));
    }

    public function getCategory()
    {
        return Category::model()->findOne(array('_id' => new MongoId($this->categoryId)));
    }

    protected function afterSave()
    {
        $image = EMongoFile::populate($this,'img');
        if(!is_null($image)) {
            $oldImage = EMongoFile::model()->findOne(array('entityId' => $this->_id));
            if(!is_null($oldImage)) $oldImage->delete();
            $image->entityId = $this->_id;
            return $image->save();
        }
    }

    protected function beforeDelete()
    {
        $image = EMongoFile::model()->findOne(array('entityId' => $this->_id));
        if(is_null($image) || $image->delete()) {
            return parent::beforeDelete();
        } else {
            return false;
        }
    }

} 

protected/controllers/ArtistController.php
<?php

class ArtistController extends Controller
{

    public function actionAdmin()
    {
        $dataProvider = new EMongoDataProvider('Artist');
        $this->render('admin', array('dataProvider' => $dataProvider));
    }

    public function actionView()
    {
        $model = $this->loadArtistModel();
        if(!is_null($model)) {
            $this->render('view', array('model' => $model));
        } else {
            $this->redirect(array('site/index'));
        }
    }

    public function actionCreate()
    {
        $model = new Artist();

        if (isset($_POST['Artist'])) {
            $model->attributes = $_POST['Artist'];
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Artist saved');
                $this->redirect('admin');
            }
        }

        $this->render('form', array('model' => $model));
    }

    public function actionDelete()
    {
        if(!Yii::app()->request->getIsAjaxRequest() || $_GET['ajax'] !== 'yw0') {
            throw new CHttpException(400, 'Not ajax request');
        }

        $model = $this->loadArtistModel();
        if(!is_null($model)) {
            if(!$model->delete()) {
                throw new CHttpException(500, 'Artist can`t be deleted');
            }
        } else {
            throw new CHttpException(400, 'Invalid request');
        }
    }

    public function actionUpdate()
    {
        $model = $this->loadArtistModel();
        if(is_null($model) && !isset($_POST['Artist'])) {
            Yii::app()->user->setFlash('message', 'Invalid request');
            $this->redirect(array('artist/admin'));
        } elseif (isset($_POST['Artist'])) {
            $model->attributes = $_POST['Artist'];
            //die(var_dump($model));
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Artist saved');
                $this->redirect(array('artist/admin'));
            }
        }

        $this->render('form', array('model' => $model));
    }

    public function actionJsonData()
    {
        if(!Yii::app()->request->getIsAjaxRequest()) {
            throw new CHttpException(400, 'Not ajax request');
        }

        $model = $this->loadArtistModel();
        if(!is_null($model)) {
            echo $model->getJSONDocument();
        } else {
            throw new CHttpException(400, 'Invalid request');
        }
    }

    private function loadArtistModel()
    {
        if(isset($_GET['id'])) {
            $id = $_GET['id'];
            $model = Artist::model()->findBy_id($id);
            if(is_null($model)) {
                throw new CHttpException(404, 'No such artist');
            }
            return $model;
        } else {
            return null;
        }
    }
}

protected/controllers/CategoryController.php
<?php

class CategoryController extends Controller
{


    public function actionAdmin()
    {
        $dataProvider = new EMongoDataProvider('Category');
        $this->render('admin', array('dataProvider' => $dataProvider));
    }

    public function actionView()
    {
        $model = $this->loadCategoryModel();
        if(!is_null($model)) {
            $this->render('view', array('model' => $model));
        } else {
            $this->redirect(array('site/index'));
        }
    }

    public function actionCreate()
    {
        $model = new Category();

        if (isset($_POST['Category'])) {
            $model->attributes = $_POST['Category'];
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Category saved');
                $this->redirect('admin');
            }
        }

        $this->render('form', array('model' => $model));
    }

    public function actionDelete()
    {
        if(!Yii::app()->request->getIsAjaxRequest() || $_GET['ajax'] !== 'yw0') {
            throw new CHttpException(400, 'Not ajax request');
        }

        $model = $this->loadCategoryModel();
        if(!is_null($model)) {
            if(!$model->delete()) {
                throw new CHttpException(500, 'Category can`t be deleted');
            }
        } else {
            throw new CHttpException(400, 'Invalid request');
        }
    }

    public function actionUpdate()
    {
        $model = $this->loadCategoryModel();
        if(is_null($model) && !isset($_POST['Category'])) {
            Yii::app()->user->setFlash('message', 'Invalid request');
            $this->redirect(array('category/admin'));
        } elseif (isset($_POST['Category'])) {
            $model->attributes = $_POST['Category'];
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Category saved');
                $this->redirect(array('category/admin'));
            }
        }

        $this->render('form', array('model' => $model));
    }

    private function loadCategoryModel()
    {
        if(isset($_GET['id'])) {
            $id = $_GET['id'];
            $model = Category::model()->findBy_id($id);
            if(is_null($model)) {
                throw new CHttpException(404, 'No such category');
            }
            return $model;
        } else {
            return null;
        }
    }
}

protected/controllers/PictureController.php
<?php

class PictureController extends Controller
{

    public function actionAdmin()
    {
        $dataProvider = new EMongoDataProvider('Picture');
        $this->render('admin', array('dataProvider' => $dataProvider));
    }

    public function actionView()
    {
        //TODO make view
        $model = $this->loadPictureModel();
        if(!is_null($model)) {
            $this->render('view', array('model' => $model));
        } else {
            $this->redirect(array('site/index'));
        }
    }

    public function actionCreate()
    {
        $model = new Picture();

        if (isset($_POST['Picture'])) {
            $model->attributes = $_POST['Picture'];
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Picture saved');
                $this->redirect('admin');
            }
        }

        $artists = Artist::model()->findAll();
        $categories = Category::model()->findAll();

        $this->render('form', array('model' => $model, 'artists' => $artists, 'categories' => $categories));
    }

    public function actionDelete()
    {
        if(!Yii::app()->request->getIsAjaxRequest() || $_GET['ajax'] !== 'yw0') {
            throw new CHttpException(400, 'Not ajax request');
        }

        $model = $this->loadPictureModel();
        if(!is_null($model)) {
            if(!$model->delete()) {
                throw new CHttpException(500, 'Picture can`t be deleted');
            }
        } else {
            throw new CHttpException(400, 'Invalid request');
        }
    }

    public function actionUpdate()
    {
        $model = $this->loadPictureModel();
        if(is_null($model) && !isset($_POST['Picture'])) {
            Yii::app()->user->setFlash('message', 'Invalid request');
            $this->redirect(array('picture/admin'));
        } elseif (isset($_POST['Picture'])) {
            $model->attributes = $_POST['Picture'];

            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Picture saved');
                $this->redirect(array('picture/admin'));
            }
        }

        $artists = Artist::model()->findAll();
        $categories = Category::model()->findAll();

        $this->render('form', array('model' => $model, 'artists' => $artists, 'categories' => $categories));
    }

    private function loadPictureModel()
    {
        if(isset($_GET['id'])) {
            $id = $_GET['id'];
            $model = Picture::model()->findBy_id($id);
            if(is_null($model)) {
                throw new CHttpException(404, 'No such picture');
            }
            return $model;
        } else {
            return null;
        }
    }
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    /**
     * Declares class-based actions.
     */
    public function actions ()
    {
        return array(

            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		$pictures = Picture::model()->find()->limit(4);
        $categories = Category::model()->findAll();
        $artists = Artist::model()->findAll();

		$this->render('index', array('pictures' => $pictures, 'categories' => $categories, 'artists' => $artists));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	public function actionImage()
    {
        if(!isset($_GET['id'])) {
            throw new CHttpException(400, 'Image id not included in request');
        }
        $id = $_GET['id'];
        $image = EMongoFile::model()->findOne(array('entityId' => new MongoId($id)));
        if(!is_null($image)) {
            header('Content-type: image/jpeg');
            echo $image->getBytes();
        } else {
            throw new CHttpException(404, 'No such image');
        }
    }
}

protected/views/picture/_pictures.php
<div class="row-fluid">

    <ul class="portfolio thumbnails ">

        <?php foreach ($pictures as $picture): ?>
        <li class="span6">
            <a href="<?php echo $this->createUrl('picture/view', array('id' => $picture->_id)) ?>" rel="lightbox"  class="thumbnail"><?php echo CHtml::image($this->createUrl('site/image', array('id' => $picture->_id)), "No image for this picture", array('class' => 'img-polaroid')); ?></a>
        </li>
        <?php endforeach; ?>
    </ul>


</div><!-- /row-fluid -->

protected/views/picture/admin.php
<?php $this->pageTitle = Yii::app ()->name . ' - Picture'; ?>

<div>
<?php
if(Yii::app()->user->hasFlash('message')) {
   echo CHtml::encode(Yii::app()->user->getFlash('message'));
}
?>
</div>

<?php

echo CHtml::link('Add picture', $this->createUrl('picture/create'));

$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $dataProvider,
    'columns' => array(
        'name:html',
        array(
            'name' => 'category',
            'value' => '$data->category->name'
        ),
        array(
            'name' => 'artist',
            'value' => '$data->artist->fullName'
        ),
        'price:html',
        array(
            'class'=>'CButtonColumn'
        )
    )
));
?>

protected/views/picture/form.php
<?php
$this->pageTitle = Yii::app ()->name . ' - Picture';

$form = $this->beginWidget ('CActiveForm', array(
    'enableClientValidation' => true,
    'clientOptions' => array(
        'validateOnSubmit' => true,
    ),
    'htmlOptions' => array(
        'name' => 'artist',
        'enctype' => 'multipart/form-data'
    )
)); ?>

<div class="row">
    <?php echo $form->textField($model, 'name', array(
        'placeholder' => $model->getAttributeLabel('name'),
    )); ?>
    <?php echo $form->error($model,'name'); ?>
</div>

<div class="row">
    <?php echo $form->textArea($model, 'description', array(
        'placeholder' => $model->getAttributeLabel('description'),
    )); ?>
    <?php echo $form->error($model,'description'); ?>
</div>

<div class="row">
    <?php echo $form->textField($model, 'price', array(
        'placeholder' => $model->getAttributeLabel('price'),
    )); ?>
    <?php echo $form->error($model,'price'); ?>
</div>

<div class="row">
    <?php echo $form->dropDownList($model, 'artistId',
        CHtml::listData($artists,
        function($artist){
            return (string) $artist->_id;
        },
        function($artist){
            return CHtml::encode($artist->fullName);
        }),
        array(
            'prompt' => $model->getAttributeLabel('artist'),
        )
    ); ?>
    <?php echo $form->error($model,'artistId'); ?>
</div>

<div class="row">
    <?php echo $form->dropDownList($model, 'categoryId',
        CHtml::listData($categories,
            function($category){
                return (string) $category->_id;
            },
            function($category){
                return CHtml::encode($category->name);
            }),
        array(
            'prompt' => $model->getAttributeLabel('category')
        )
    ); ?>
    <?php echo $form->error($model,'categoryId'); ?>
</div>

<div class="row">
    <?php echo $form->labelEx($model,'img'); ?>
    <?php echo $form->fileField($model, 'img'); ?>
    <?php echo $form->error($model,'img'); ?>
</div>

<?php echo CHtml::submitButton ('Save'); ?>

<?php $this->endWidget (); ?>

protected/views/picture/view.php
<?php $this->pageTitle = Yii::app ()->name . ' - ' . $model->name; ?>

<div class="page-header">
    <h1><?php echo CHtml::encode($model->name) ?></h1>
</div>


<div class="blog-image"><?php echo CHtml::image($this->createUrl('site/image', array('id' => $model->_id)), "No image for this picture", array('class' => 'img-polaroid')); ?></div>

<div class="row-fluid">
    <div class="span12">
        <h3 class="header"><?php echo $model->getAttributeLabel('description') ?>
            <span class="header-line"></span>
        </h3>
        <?php echo CHtml::encode($model->description) ?>
    </div>

</div><!--/row-fluid-->

<div class="row-fluid">
    <div class="span12" id="contactInfo">
        <h3 class="header">Price - <?php echo CHtml::encode($model->price) ?>



<?php echo CHtml::ajaxButton('Buy', $this->createUrl('artist/jsonData', array('id' => $model->artistId)),
    array(
        'dataType' => 'json',
        'error' => 'js:function(obj, err) {
            $("#contactInfo").append("Artist contacts can`t be reached");
        }',
        'success' => 'js:function(data) {
            $("#contactInfo").append("<div>Contacts:</div><div>E-mail: "+data.email+"</div><div>Phone: "+data.phone+"</div><div>Skype: "+data.skype+"</div>");
            $("#contact").hide();
        }'
    ),
    array(
        'id' => 'contact',
        'class' => 'btn btn-primary'
    )
    );
?>
            <span class="header-line"></span>
        </h3>
    </div>

</div><!--/row-fluid-->

<div class="row-fluid">
    <div class="span12">
        <h3 class="header">Artist - <?php echo CHtml::link(CHtml::encode($model->artist->fullName), $this->createUrl('artist/view', array('id' => $model->artistId))) ?>
    <span class="header-line"></span>
    </h3>
</div>

</div><!--/row-fluid-->

<div class="row-fluid">
    <div class="span12">
        <h3 class="header">Category - <?php echo CHtml::link(CHtml::encode($model->category->name), $this->createUrl('category/view', array('id' => $model->categoryId))) ?>
    <span class="header-line"></span>
    </h3>
</div>