protected/models/Category.php
<?php
/**
 *  Category - model to store categories in mongodb.
 */

class Category extends EMongoDocument {

    public $name;

    public function collectionName()
    {
        return 'categories';
    }

    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function rules()
    {
        return array(
            array('name', 'required'),
            array('name', 'type', 'type' => 'string'),
            array('name', 'length', 'max' => 20)
        );
    }

    public function attributeNames()
    {
        return array('name');
    }

    public function attributeLabels()
    {
        return array(
            'name'     => 'Name',
        );
    }

    public function getPictures()
    {
       return Picture::model()->findAll(array('categoryId' => (string) $this->_id));
    }

    protected function beforeDelete()
    {
        if(Picture::model()->deleteAll(array('categoryId' => (string) $this->_id))){
            return parent::beforeDelete();
        } else {
            return false;
        }
    }
} 

protected/controllers/CategoryController.php
<?php

class CategoryController extends Controller
{


    public function actionAdmin()
    {
        $dataProvider = new EMongoDataProvider('Category');
        $this->render('admin', array('dataProvider' => $dataProvider));
    }

    public function actionView()
    {
        $model = $this->loadCategoryModel();
        if(!is_null($model)) {
            $this->render('view', array('model' => $model));
        } else {
            $this->redirect(array('site/index'));
        }
    }

    public function actionCreate()
    {
        $model = new Category();

        if (isset($_POST['Category'])) {
            $model->attributes = $_POST['Category'];
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Category saved');
                $this->redirect('admin');
            }
        }

        $this->render('form', array('model' => $model));
    }

    public function actionDelete()
    {
        if(!Yii::app()->request->getIsAjaxRequest() || $_GET['ajax'] !== 'yw0') {
            throw new CHttpException(400, 'Not ajax request');
        }

        $model = $this->loadCategoryModel();
        if(!is_null($model)) {
            if(!$model->delete()) {
                throw new CHttpException(500, 'Category can`t be deleted');
            }
        } else {
            throw new CHttpException(400, 'Invalid request');
        }
    }

    public function actionUpdate()
    {
        $model = $this->loadCategoryModel();
        if(is_null($model) && !isset($_POST['Category'])) {
            Yii::app()->user->setFlash('message', 'Invalid request');
            $this->redirect(array('category/admin'));
        } elseif (isset($_POST['Category'])) {
            $model->attributes = $_POST['Category'];
            if ($model->validate() && $model->save()) {
                Yii::app()->user->setFlash('message', 'Category saved');
                $this->redirect(array('category/admin'));
            }
        }

        $this->render('form', array('model' => $model));
    }

    private function loadCategoryModel()
    {
        if(isset($_GET['id'])) {
            $id = $_GET['id'];
            $model = Category::model()->findBy_id($id);
            if(is_null($model)) {
                throw new CHttpException(404, 'No such category');
            }
            return $model;
        } else {
            return null;
        }
    }
}

protected/views/category/admin.php
<?php $this->pageTitle = Yii::app ()->name . ' - Category'; ?>

<div>
<?php
if(Yii::app()->user->hasFlash('message')) {
   echo CHtml::encode(Yii::app()->user->getFlash('message'));
}
?>
</div>

<?php

echo CHtml::link('Add category', $this->createUrl('category/create'));

$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $dataProvider,
    'columns' => array(
        'name:html',
        array(
            'class'=>'CButtonColumn'
        )
    )
));
?>

protected/views/category/form.php
<?php
$this->pageTitle = Yii::app ()->name . ' - Category';

$form = $this->beginWidget ('CActiveForm', array(
    'enableClientValidation' => true,
    'clientOptions' => array(
        'validateOnSubmit' => true,
    ),
    'htmlOptions' => array(
        'name' => 'category',
    )
)); ?>

<div class="row">
    <?php echo $form->textField($model, 'name', array(
        'placeholder' => $model->getAttributeLabel('name'),

    )); ?>
    <?php echo $form->error($model,'name'); ?>
</div>

<?php echo CHtml::submitButton ('Save'); ?>

<?php $this->endWidget (); ?>

protected/views/category/view.php
<?php $this->pageTitle = Yii::app ()->name . ' - ' . $model->name; ?>

<div class="page-header">
    <h1><?php echo CHtml::encode($model->name) ?></h1>
</div>

<?php $this->renderPartial('//picture/_pictures', array('pictures' => $model->pictures)); ?>

</div><!-- /row-fluid -->